### ISSUE TITLE
Get package to CRAN

### ISSUE THREAD

**Issue by angela-li** [spatialanalysis/geodaData#7]
I'd love some support reviewing this geospatial data package before trying to submit it to CRAN! I plan to go through and check it according to the [rOpenSci packaging guide](https://devguide.ropensci.org), but would love some input from those who have submitted geospatial data packages to CRAN before.

@Nowosad @Robinlovelace I love what you did with spData, do you have any advice (general or specific) for making this package better for CRAN?

**Comment by Robinlovelace** [comment]
Looks good to me, I suggest sending testing it on https://builder.r-hub.io/. CRAN is quite fussy about the DESCRIPTION file so watch-out. Guidance: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file this is also really useful: https://r-pkgs.org/

**Comment by Robinlovelace** [comment]
On question where you may be able to help me: how did you get the website autobuild going? Looks to me like it's on the GitHub platform, never seen that before and if it can take the pain out of travis auto-deploy I'm interested! This is what get when clicking the green ticks:

![image](https://user-images.githubusercontent.com/1825120/72295451-8337a600-364f-11ea-96d4-ceba15c3fbcb.png)

**Comment by Robinlovelace** [comment]
Another tip for fun not CRAN, if you add

```r
plot(dataset)
```

For each of your datasets it will make the website contain lots of maps, e.g. at the bottom of this page (this is what we did with `spData`):

https://spatialanalysis.github.io/geodaData/reference/guerry.html

**Comment by Robinlovelace** [comment]
Final update, this shows our mission to get the package on CRAN, you can see various changes to the DESCRIPTION and more in the runup to 2017-07-23 when it went up: https://github.com/Nowosad/spData/compare/master@%7B2017-06-01%7D...master@%7B2017-07-23%7D

**Comment by Robinlovelace** [comment]
Final final update :smile: 

> On question where you may be able to help me: how did you get the website autobuild going?

Aha, OK in answer to my previous question it looks like it's deploying from the `docs` folder: https://github.com/spatialanalysis/geodaData/tree/master/docs

The `tic` package can with setup of autodeploy although that can be a bit of hassle. Good luck and let us know how you get on!

**Comment by angela-li** [comment]
Thank you for these resources and advice Robin! Yes, the pkgdown website is just Github Pages built-in functionality for `docs`, nothing fancy. Will take a look at everything later this weekend. And then I'll try to make changes and submit (fingers crossed) to CRAN...

**Comment by angela-li** [comment]
I submitted the package to CRAN!! 🎉 🎉 🎉  My first ever submission 😮 Thanks for all the help along the way!

**Comment by Robinlovelace** [comment]
Great to hear @angela-li, :crossed_fingers: the 'CRAN Gods' look kindly on geodaData, it's a cool package and will encourage others to package their code/data in a way that is more accessible/useful for others :tada:
